mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.lc.Entity

server:
  port: 1224

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.122.6
    port: 6379
    password: 123
    database: 3
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

    # 自定义配置：启动时自动打开浏览器访问的URL
openProject:
  isOpen: true
  cmd: cmd /c start
  web:
    openUrl: http://localhost:1224/index


